---
- name: Create openstack dir
  file:
    path: /etc/openstack
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - openstack-exporter

- name: Write clouds config
  notify:
    - Restart openstack-exporter
  template:
    src: config.j2
    dest: /etc/openstack/clouds.yaml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - openstack-exporter

- name: Write default config
  notify:
    - Restart openstack-exporter
  template:
    src: default.j2
    dest: /etc/default/openstack-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - openstack-exporter

- name: Prepare service file
  notify:
    - Restart openstack-exporter
  template:
    src: service.j2
    dest: /etc/systemd/system/openstack-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - openstack-exporter

- name: Pull docker image
  when:
    - openstack_exporter_pull_image
  docker_image:
    name: "{{ openstack_exporter_image }}"
    source: pull
  tags:
    - openstack-exporter

- name: Create docker network
  when:
    - openstack_exporter_network | default(False)
  docker_network:
    name: '{{ openstack_exporter_network }}'
  tags:
    - openstack-exporter

- name: Start exporter service
  systemd:
    name: openstack-exporter
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - openstack-exporter

...
